### ISSUE TITLE
Nach 2022 wird nur noch "Januar 1970" angezeigt

### ISSUE THREAD

**Issue by Sabse83** [FriendsOfREDAXO/avcal#6]
Hallo, ich habe diesen Kalender bei einer Webseite im Einsatz und bin auf ein Problem gestoßen, dass ihn bald unbrauchbar macht:

Auf der ersten Seite der Kalenderansicht wird alles nach Dezember 2022 nur als Januar 1970 angezeigt.
Sobald man auf eine andere Seite blättert, egal ob im Backend oder Frontend ist wieder alles richtig.

![avcal-fehler](https://user-images.githubusercontent.com/96485558/147104525-9c93817a-d832-4add-b23f-3f2203b03201.jpg)

**Comment by Sabse83** [comment]
Anscheinend hat sich das Problem zum Jahresanfang auf 2024 verschoben, also kann man den Fehler umgehen, indem man nie mehr als 12 Monate auf einer Seite ausgeben lässt.

**Comment by skerbis** [comment]
kann ich bei mir nicht reproduzieren
